CREATE TABLE IF NOT EXISTS products (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	categoryid BIGINT NOT NULL,
	modelnumber BIGINT NOT NULL,
	productimage TEXT,
	price DOUBLE PRECISION NOT NULL,
	description TEXT,
	productiondate DATE NOT NULL,
    quantity INT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS categories (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	categoryname TEXT NOT NULL,
	description TEXT,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS orders (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	clientid BIGINT NOT NULL,
	orderdate TIMESTAMPTZ NOT NULL,
	shipdate TIMESTAMPTZ,
	statusid BIGINT NOT NULL,
	orderprice DOUBLE PRECISION NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS clients (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL,
	address TEXT NOT NULL,
	email TEXT NOT NULL,
	phonenumber TEXT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS orderdetails (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	orderid BIGINT NOT NULL,
	productid BIGINT NOT NULL,
	unitprice DOUBLE PRECISION NOT NULL,
	quantity INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS statuses (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	statusname TEXT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS models (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	modelname TEXT NOT NULL,
	parameters TEXT,
	PRIMARY KEY(id)
);

alter table products
    add constraint Products_Categories_CategoryID_fk
        foreign key (categoryid) references categories;
alter table orders
    add constraint Orders_Clients_ClientID_fk
        foreign key (clientid) references clients;
alter table orders
    add constraint Orders_Statuses_StatusID_fk
        foreign key (statusid) references statuses;
alter table orderdetails
    add constraint OrderDetails_Orders_OrderID_fk
        foreign key (orderid) references orders;
alter table products
    add constraint Products_Models_ModelNumber_fk
        foreign key (modelnumber) references models;
